require:
  - rubocop-rails
  - rubocop-performance

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - vendor/**/*

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either
